import time
input("Enter The username:")
print ("==============starting Hack==============")
time.sleep(0.5)
print ("====            Hack (1)             ====")
time.sleep(0.5)
print ("====            Hack (2)             ====")
print ("====            Hack (3)             ====")
time.sleep(0.5)
print ("====            Hack (4)             ====")
time.sleep(0.5)
print ("====            Hack (5)             ====")
time.sleep(0.5)
print ("====            Hack (6)             ====")
print ("====            Hack (7)             ====")
print ("====            Hack (8)             ====")
time.sleep(0.5)
print ("====            Hack (9)             ====")
time.sleep(0.5)
print ("====            Hack (10)            ====")
time.sleep(0.5)
print ("====            Hack (12)            ====")
time.sleep(1)
print ("====            Hack (13)            ====")
print ("====            Hack (14)            ====")
time.sleep(0.5)
print ("====            Hack (15)            ====")
print ("====            Hack (16)            ====")
time.sleep(0.5)
print ("====            Hack (17)            ====")
print ("====            Hack (18)            ====")
time.sleep(0.5)
print ("====            Hack (19)            ====")
time.sleep(3)
print ("=================HACKED==================")
print("                                \|||/")
print("         .-._________           (o o)             ________.-.")
print("     ----/ \_)_______)  + -oooO--(_)--------- + (_______(_/ \----")
print("        (    ()___)     | Please Visit Us At: |    (___()    )")
print("             ()__)      |                     |     (__()")
print("     ----\___()_)       |  github.com/ali0518 |      (_()___/----")
print("                        + ---------------Ooo- +")
input("Press Enter To Exit")
